const express = require('express');
const path = require('path');
const fs = require('fs');

const app = express();
const PORT = process.env.MOCK_API_PORT || 4000;

// Load cases JSON (generated by scripts/generate_cases.js)
const casesPath = path.resolve(__dirname, '..', 'src', 'mocks', 'cases.json');
let cases = [];
if (fs.existsSync(casesPath)) {
  try {
    cases = JSON.parse(fs.readFileSync(casesPath, 'utf8'));
  } catch (err) {
    console.error('Failed to parse cases.json', err);
  }
} else {
  console.warn('cases.json not found at', casesPath);
}

function paginateAndFilter(req) {
  const page = Math.max(1, parseInt(req.query.page || '1', 10));
  const pageSize = Math.max(1, Math.min(100, parseInt(req.query.pageSize || '10', 10)));
  const priority = req.query.priority;

  let filtered = cases.slice();
  if (priority) filtered = filtered.filter((c) => c.priority === priority);
  filtered.sort((a, b) => new Date(b.submittedAt).getTime() - new Date(a.submittedAt).getTime());
  const total = filtered.length;
  const limited = filtered.slice(0, 100);
  const start = (page - 1) * pageSize;
  const paged = limited.slice(start, start + pageSize);
  return { cases: paged, total: Math.min(total, 100) };
}

app.get('/api/cases', (req, res) => {
  const out = paginateAndFilter(req);
  res.json(out);
});

app.listen(PORT, () => {
  console.log(`Mock API server listening on http://localhost:${PORT}`);
});
